### PR TITLE
Add arguments to artisan commands

### PR DESCRIPTION
**Pull request by cwray-tech**
I updated a couple of the artisan command examples that need arguments to create a connector and request. It would be nice to have a doc page for the Laravel package with details of the commands available as well, but maybe this would be a good start.

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Thanks for this! I think I might make my own page for the full details of artisan commands, then make these examples that link to the full example?

**Comment by cwray-tech** [comment]
@Sammyjo20 yeah that's probably the best route! (:

**Comment by Sammyjo20** [comment]
Awesome! I’ll get that drafted up, will close this when its done. Thank you for the positive feedback, that’s very kind!

**Comment by Sammyjo20** [comment]
This is added to the docs now so I will close this

**Pull request closed without merging**
